version: "3"
services:
  java:
    build: .
    container_name: java
#    env_file:
#      - ./mysql/db.env # mysqlと同じものを指定
    tty: true
    working_dir: /app
    volumes:
      - $PWD:/app # Spring Bootのプロジェクト
    ports:
      - 8080:8080 # 通常実行
      - 5050:5050 # デバッグ用